#resources:
#  App\Entity\Book:
    #operations:
    #  ApiPlatform\Metadata\GetCollection:
    #    method: GET
    #    groups: ['get_all']
      #ApiPlatform\Metadata\Get:
      #  method: GET
      #  groups: ['get_one']



